description = "Initializ Distroless base image with buildpacks for Go, NodeJS,Python, Ruby, Java, .NET Core, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "index.docker.io/initializbuildpacks/python@sha256:7aaeada4cd13f04f4e5ff570bb80328515d335550a309979bf82b3bb229ef07c"
  version = "4.0.4"

[lifecycle]
  version = "0.19.3"

[[order]] 

  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.4"


# Base images used to create the builder
[stack]
  build-image = "janisar/securepacks-build:latest"
  id = "Initializ Distroless Stack"
  run-image = "janisar/securepacks-run:latest"
  run-image-mirrors = []
