on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string

jobs:
  update-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Set up Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.3
        with:
          version: 0.33.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Builder to Docker Hub
        run: |
          pack builder create initializbuildpacks/securepacks-${{ inputs.image }}:latest --config ./securepacks/${{ inputs.image }}/builder.toml
          docker push janisar/securepacks-${{ inputs.image }}:latest
